
version: '3.8'

services:
  db:
    image: postgres:17-bookworm
    container_name: bot_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .env
      - .env.prod 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    image: my-telegram-bot:local 
    container_name: my_pro_bot
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
      - .env.prod 
    volumes:
      - ./:/app 
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:

