"""first chages

Revision ID: 4f4ab24e5d76
Revises: c79f3e2b6a36
Create Date: 2026-04-02 22:35:20.622998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4ab24e5d76'
down_revision: Union[str, Sequence[str], None] = 'c79f3e2b6a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_bytes', sa.BigInteger(), nullable=False),
    sa.Column('change_requests', sa.Integer(), nullable=False),
    sa.Column('io', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('users', 'remaining_searches')
    op.drop_column('users', 'remaining_bytes')
    op.drop_column('users', 'is_pro')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_pro', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('remaining_bytes', sa.BIGINT(), nullable=True))
    op.add_column('users', sa.Column('remaining_searches', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    # ### end Alembic commands ###
